### ISSUE TITLE
Seiten filtern?

### ISSUE THREAD

**Issue by ngdot** [cliffparnitzky/DirectContentElements#10]
Hi, wäre es möglich Content Elemente eines Seitenbaums zu filtern?

**Comment by mecintosch** [comment]
Mein Feature-Request geht in die selbe Richtung.

Toll wärs wenn man alle Artikel-Inhaltselemente rausfiltern könnte die einen gewissen Suchbegriff im Artikel-Titel haben. Danke!

**Comment by cliffparnitzky** [comment]
Prinzipiell wird hier nur gehen, was der Standard DCA auch kann.

Ob diese 2 Wünsche umsetzbar sind, prüfe ich bei Zeiten mal.
