### ISSUE TITLE
Dependencies Events and News

### ISSUE THREAD

**Issue by rustykowski** [cliffparnitzky/DirectContentElements#11]
Da sich Contao inzwischen auch ohne News- und Events-Bundles installieren lässt, kann es zu Installationproblemen kommen. In meinem Fall brach die Installation mit einem Fehler ab: "The module folder "system/modules/calendar" does not exist.", ausgelöst von einer scripthandler.php (oder ähnlich).
Entweder sollten also diese Abhängigkeiten hinzugefügt werden, oder die Installationsroutine sollte das eventuelle Nichtvorhandensein dieser Bundles berücksichtigen.

**Comment by Aybee** [comment]
In diese Falle bin ich auch gerade gelaufen. Reicht es, wenn ich die Abhängigkeiten erstmal manuell hinzufüge? Welche wären das?

**Comment by Aybee** [comment]
Habe news und calendar jetzt nachinstalliert. Contao 4.4.38
```json
...
"cliffparnitzky/direct-content-elements": "^1.2",
"contao/calendar-bundle": "^4.4",
"contao/news-bundle": "^4.4",
...
```
Das geht erstmal, wäre aber schön, wenn es auch ohne news und calendar gehen würde.

**Comment by cliffparnitzky** [comment]
Umsetzungsnotiz:

- Entfernen: https://github.com/cliffparnitzky/DirectContentElements/blob/master/system/modules/DirectContentElements/config/autoload.ini#L5-L6
- Entsprechend absichern: https://github.com/cliffparnitzky/DirectContentElements/blob/master/system/modules/DirectContentElements/config/config.php#L48-L76

**Comment by cliffparnitzky** [comment]
@rustykowski @Aybee Könnte ihr bitte mal den `dev-feature/1.3.0` via Contao Manager installieren und testen, ob das soweit den Erwartungen entspricht. Vielen Dank.

**Comment by Aybee** [comment]
Contao 4.4.40 **erfolgreich** getestet. Danke.

Contao 4.7 konnte ich gerade auf Webgo nicht installieren.

**Comment by cliffparnitzky** [comment]
Version 1.3.0 ist mit dieser Verbesserung verfügbar. Viel Spaß damit.
