### ISSUE TITLE
Backend navigation label improvement

### ISSUE THREAD

**Issue by Aybee** [cliffparnitzky/DirectContentElements#12]
Hallo Cliff, wäre es möglich diese Sprachbausteine zu kürzen?
https://github.com/cliffparnitzky/DirectContentElements/blob/master/system/modules/DirectContentElements/languages/de/modules.php#L34-L36

Sieht nicht so gut aus, weil es so lang ist und dadurch auch zweispaltig wird. `Inhaltselemente` dürfte IMHO reichen, was meinst du, oder die anderen?

**Comment by cliffparnitzky** [comment]
Ich hatte das mal testweise geändert, aber es sah nicht wirklich gut aus ... und war auch etwas verwirrend weil dann da steht:

- Artikel
  - Inhaltselemente
- Events
  - Inhaltselemente
- Nachrichten
  - Inhaltselemente

Außerdem wird das hier im Seitentitel ja auch verwendet:

![image](https://user-images.githubusercontent.com/1247552/56894618-bcf75b00-6a86-11e9-8ee3-8ac05aecfe28.png)

**Comment by Aybee** [comment]
Mmh, ok. Aber schön ist das natürlich nicht. Und wenn man Inhaltselement mit CE abkürzt? Da ist ja noch der Tooltip, der es näher erläutert.

Hier ein paar Vorschläge
_
1. Alle Artikel CEs
2. Alle Event CEs
3. Alle News CEs

_
1. Mehrere bearbeiten
2. Mehrere bearbeiten
3. Mehrere bearbeiten

_
1. Alle Inhaltselemente
2. Alle Inhaltselemente
3. Alle Inhaltselemente

**Comment by Aybee** [comment]
Ja, super, danke.
