### ISSUE TITLE
Undefined array key "do"

### ISSUE THREAD

**Issue by rabauss** [cliffparnitzky/DirectContentElements#14]
All the checks with `$_GET['do']` etc. will throw an error in php 8 with activated debug mode:
https://github.com/cliffparnitzky/DirectContentElements/blob/1631d9f3ba2014528bd8767f9e43186f534c4802/system/modules/DirectContentElements/config/config.php#L39

**Comment by dennisbohn** [comment]
This should fix the error.

https://github.com/cliffparnitzky/DirectContentElements/pull/15
