### ISSUE TITLE
error after switching to PHP 7.2

### ISSUE THREAD

**Issue by GeccoDesign** [cliffparnitzky/DirectContentElements#9]
Hi, I got an error after switching to PHP 7.2

`Warning: count(): Parameter must be an array or an object that implements Countable in system/modules/DirectContentElements/config/config.php on line 33

#0 system/modules/DirectContentElements/config/config.php(33): __error(2, 'count(): Parame...', '/mnt/web218/e3/...', 33, Array)
#1 system/modules/core/library/Contao/Config.php(141): include('/mnt/web218/e3/...')
#2 system/modules/core/library/Contao/Config.php(108): Contao\Config->initialize()
#3 system/initialize.php(162): Contao\Config::getInstance()
#4 index.php(16): require('/mnt/web218/e3/...')
#5 {main}`

Contao installation 3.5.36, provider Strato.
What can I do? Thank you.

**Comment by cliffparnitzky** [comment]
Yes, that is right, this extension is currently not compatible to PHP 7.2. This has to fixed in the code.
